name: "Test Multiple Python Versions"
on:
  push:
    branches:
      - main  # Specify the branch that the workflow will respond to
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
      - uses: actions/checkout@v3  # Update to version 3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4  # Update to version 4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make install
      - name: Lint with pylint
        run: |
          make lint
      - name: Test with pytest
        run: |
          make test
      - name: Format code with Black
        run: |
          make format
